version: '3.3'
services:
  otp:
    image: urbica/otp
    restart: unless-stopped
    ports:
      - 8081:8080
    volumes:
      - ./graphs:/var/otp/graphs
    environment:
      - JAVA_OPTIONS=-Xmx8G
    command:
      [
        '--server',
        '--maxThreads 4',
        '--analyst',
        '--autoScan',
        '--insecure',
        '--verbose'
      ]
